---
dist: bionic
language: python

# Cache the big Vagrant boxes
cache:
  directories:
    - /home/travis/.vagrant.d/boxes

env:
  global:
    - ROLE_NAME: localization

install:
  # Install libvrt & KVM (see
  # github.com/alvistack/ansible-role-virtualbox/blob/master/.travis.yml)
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base
    ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

  # Download Vagrant & Install Vagrant package
  - sudo wget -nv
    https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb

  # Vagrant correctly installed?
  - vagrant --version

  # Install vagrant-libvirt Vagrant plugin
  - sudo vagrant plugin install vagrant-libvirt

  - pip install molecule==2.22 docker python-vagrant

  - git clone https://github.com/arillso/tests molecule/default/lint

before_script:
  - cd ../
  - mv ansible.$ROLE_NAME arillso.$ROLE_NAME
  - cd arillso.$ROLE_NAME
  - sudo chown -R travis /home/travis/.vagrant.d
  - find /home/travis/.vagrant.d/data
  - find /home/travis/.vagrant.d/data | xargs ls -l
  - sudo usermod -a -G libvirtd $USER
  - sudo cat /etc/group | grep $USER

script:
  - molecule test -s windows

after_failure:
  - LOGF=/home/travis/.cache/molecule/arillso.localization/windows/vagrant-vagrant-win2012r2.err
  - if [ -f $LOGF ]; then cat $LOGF; fi

notifications:
  email:
    on_success: never
    on_failure: always
